# Generated by Django 5.0.3 on 2024-04-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_version_current_version_indication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='name',
            new_name='version_name',
        ),
        migrations.AddField(
            model_name='product',
            name='publication_sign',
            field=models.BooleanField(default=False, verbose_name='Признак публикации'),
        ),
    ]
