# Generated by Django 5.0.3 on 2024-04-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_rename_name_version_version_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publication_sign',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Признак публикации'),
        ),
    ]
