# Generated by Django 4.2 on 2024-04-27 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_ban_publish_products', 'Can ban posts'), ('can_change_description_product', 'can change description'), ('can_change_category_product', 'can change category')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
